### ISSUE TITLE
Pre blocks generally don't stack together

### ISSUE THREAD

**Issue by badlydrawnrob** [badlydrawnrob/print-first-css#41]
> I think originally I added this because of the Anki Themes layout.
>
> - div wrappers have no padding or margins
> - `pre` tags have **`padding` only** (no margins)
>
> Two code blocks in Anki Themes will stack together with no gaps.

The following `code.less` is using **negative `margin-top`**:

```less
  & + & {
    border-top: transparent;
    margin-top: calc(var(--spacing) * -1);  // #2
  }
```

I expect my thinking was to make sure that two `pre` blocks together would stack up without a gap ... only, while using Pandoc the `<div class="sourceCode">` for [Skylighting](#38) the `pre` blocks **are never going to be right next to each other!**

```css
div.sourceCode {
  margin: 1em 0;
}
```

The above code is what Skylighting wrapper will do; two `pre` blocks rendered with Pandoc will produce a gap.
